# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

diawi_token = ENV["DIAWI_TOKEN"]
git_url = ENV["FASTLANE_GIT"]
app_identifier = "br.com.blu.ocean.DesignSystem"

platform :ios do
  desc "Description of what the lane does"
  lane :upload_to_diawi do
    get_profiles_step()
    archive_app_step()
    upload_diawi_step()
  end

  private_lane :get_profiles_step do 
    match(
      git_url: git_url,
      app_identifier: app_identifier,
      type: "adhoc", 
      readonly: false
    )
  end

  private_lane :archive_app_step do 
    gym( 
      scheme: "OceanDesignSystem",
      export_method: "ad-hoc"
    )
  end

  private_lane :upload_diawi_step do 
    diawi(
      token: diawi_token
    )
  end
end
