# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

scheme = "OceanDesignSystem"
team = "57KSFR5UHN"
adhoc_provision_profile = "match AdHoc br.com.blu.ocean.DesignSystem"
appstore_provision_profile = "match AppStore br.com.blu.ocean.DesignSystem"
bundle_identifier = "br.com.blu.ocean.DesignSystem"

platform :ios do
  desc "Mandatory for use in circle-ci"
  before_all do
    
    setup_circle_ci

  end

  desc "Build and Test App"
  lane :build_test do 
    run_tests(scheme: "OceanDesignSystem")
  end

  desc "Upload to TestFlight"
  lane :beta_testflight do
    update_code_signing_settings(
      use_automatic_signing: false
    )

    api_key = app_store_connect_api_key(
      key_id: "#{ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"]}",
      issuer_id: "#{ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"]}",
      key_content: "#{ENV["APP_STORE_CONNECT_API_KEY_KEY"]}".gsub('\n', '\\n'),
      in_house: false
    )
    
    get_certificates(
      api_key: api_key,
      development: true
    )
    
    increment_build_number()
    
    get_profiles_step(type: 'appstore')
    
    archive_app_step(
      export_method: 'app-store', 
      bundle_identifier: bundle_identifier, 
      provision_profile: appstore_provision_profile, 
      team: team 
    )

    upload_testflight_step()

  end

  desc "Prepare version"
  lane :prepare_release do
    #build_version = increment_build_number()
    build_version = increment_build_number()
    #build_version = latest_testflight_build_number().to_s
    version = get_version_number()
    newTag = "OceanDesignSystem-" + version + "-" + build_version
    puts(newTag)
  end

  private_lane :get_profiles_step do |options|
    match(
      type: options[:type],#"adhoc"
      readonly: is_ci
    )
  end

  private_lane :archive_app_step do |options|

    settings_to_override = {
      :BUNDLE_IDENTIFIER => options[:bundle_identifier],
      :PROVISIONING_PROFILE_SPECIFIER => options[:provision_profile],
      :DEVELOPMENT_TEAM => options[:team]
    }

    gym( 
      scheme: scheme,
      export_method: options[:export_method],
      xcargs: settings_to_override
    )
  end

  private_lane :upload_diawi_step do 
    diawi(
      token: diawi_token,
      password: diawi_password
    )
  end

  private_lane :upload_testflight_step do 
    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false,
      run_precheck_before_submit: false
    )
  end
end
