# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

diawi_token = ENV["DIAWI_TOKEN"]
# git_url = ENV["FASTLANE_GIT"]
# app_identifier = "br.com.blu.ocean.DesignSystem"
scheme = "OceanDesignSystem"

platform :ios do
  desc "Mandatory for use in circle-ci"
  before_all do
    setup_circle_ci
  end

  desc "Description of what the lane does"
  lane :beta_diawi do
    get_profiles_step(type: 'development')
    get_profiles_step(type: 'adhoc')
    archive_app_step(export_method: 'ad-hoc')
    upload_diawi_step()
  end
  desc "Upload to TestFlight"
  lane :beta_testflight do
    increment_build_number()
    get_profiles_step(type: 'appstore')
    archive_app_step(export_method: 'app-store')
    upload_testflight_step()
  end

  private_lane :get_profiles_step do |options|
    match(
      type: options[:type],#"adhoc"
      readonly: true
    )
  end

  private_lane :archive_app_step do |options|
    gym( 
      scheme: scheme,
      export_options: {
	signingStyle: "automatic"
      }
    )
  end

  private_lane :upload_diawi_step do 
    diawi(
      token: diawi_token
    )
  end

  private_lane :upload_testflight_step do 
    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )
  end
end
